# Generated by Django 4.1.3 on 2022-11-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
